# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: ""

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Australia/Melbourne


# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: posts

tagline: sublimeclemency

description: >- # used by seo meta and the atom feed
  posts by sublimeclemency


# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: "https://sublimeclemency.github.io"
img_path: /assets/img
github:
  username: sublimeclemency
twitter:
  username: sublimeclemency

social:
  name: sublimeclemency
  email: sublimeclemency@gmail.com
  links:
    - https://twitter.com/sublimeclemency
    - https://github.com/sublimeclemency

google_site_verification: # fill in to your verification string
# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id: G-LF1FS4QWGN
  # Google Analytics pageviews report settings
  pv:
    proxy_endpoint: # fill in the Google Analytics superProxy endpoint of Google App Engine
    cache_path: # the local PV cache data, friendly to visitors from GFW region

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
theme_mode:

# 启用动画背景特效
backgroud_animation: true

# 启用鼠标点击特效
mouse_click_effect: false

# 图像 CDN 端点。
# 注意一旦被分配，CDN 网址会被加在
# 所有以 '/' 开始的图像（网站头像和帖子中的图像）路径上
# 
# 例如，'https://cdn.com'
img_cdn: ""

# 侧边栏的头像，支持本地或 CROS 资源
avatar: /index.jpg

# 设置显示右侧边栏的内容
panel:
  # 设置显示在帖子中右侧边栏的内容
  # 
  # 提示:
  #   全局开关为 false 时必定不显示对应块。
  #   全局开关为 true 时，可以在帖子的 md 文件头部使用形如:
  #      lastmod: false
  #   的方式为该帖子单独关闭右侧边栏的功能。
  post:
    # 最近更新
    lastmod: true
    # 热门标签
    trending_tags: false
    # 外部链接
    external_links: false
    # 目录
    toc: true

comments:
  active: utterances
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: sublimeclemency/utterances # <gh-username>/<repo>
    issue_term: url # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  waline:
    server: # Vercal 服务端地址
    placeholder: say something! # 空白评论框时显示的文字
    avatar: mp # 默认头像  › https://waline.js.org/guide/client/avatar.html
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`


# 自托管静态资产，可选 › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # 布尔值, 置空表示否
    # 指定 Jekyll 环境，置空意味着都启用
    # 仅在 `assets.self_host.enabled` 为 'true' 时生效
    env: # [development|production]

pwa:
  enabled: true # PWA 特性选项

# 每一页的帖子数量
paginate: 9

# ------------ 下面的设置不建议修改 ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge 设置 › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  - scope:
      path: "" # 空字符串意味着项目里的所有文件
      type: posts
    values:
      layout: post
      comments: true # 在帖子中启用评论
      # 右侧边栏的默认显示
      lastmod: true
      trending_tags: true
      external_links: true
      toc: true
      license: true
      # 不要改变它除非你是 Jekyll 以及 Web 开发的专家，
      # 或者你认为自己足够聪明可以在此模板中修改为其他的相对路径。
      permalink: /posts/:title/
      applause_button: true
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true
sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/